// @ai:generated by=claude-opus-4-8 date=2026-06-19
package services

// func_nodes.go：把「帶 @ai 標註」的函式抽成 Obsidian 的行為說明節點（一函式一筆記）。
//
// 設計用意——讓 GoMap 完全服務於 HypGo：函式是「行為」的最小單位，HypGo 的 @ai 標註
// 又承載了該行為的意圖 (intent)、約束 (constraint)、副作用 (sideeffect) 等語意。把這些
// 函式做成節點並由套件筆記 [[wikilink]] 連過去，HypGo 專案的「為什麼」就直接出現在
// Obsidian 關係圖裡。
//
// 重用 HypGo：doc 區塊的 @ai:* 標註直接用 pkg/annotation.ParseAnnotations 解析（與框架
// 同一套文法）；body 內的 //@ai:think 因 pkg/annotation 不輸出其內容（只做缺漏檢查），
// 故依 HypGo 的 bodyHasThink 慣例自行擷取原文帶入筆記。
//
// 節點條件（依使用者選擇）：函式帶任何 @ai 標註才建節點；並排除 @ai:generated by=hypgo
// 的框架生成碼（「非 HypGo」——框架自產的膠水不算使用者行為）。

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/annotation"
)

// funcNode 是單一函式的行為說明節點所需的全部資料。
type funcNode struct {
	display    string                  // 顯示名：func 名，或方法的 "(*T).Method"
	noteName   string                  // 筆記檔名（不含 .md），唯一
	pkgNote    string                  // 所屬套件筆記名
	pkgName    string                  // 套件名
	importPath string                  // 套件 import path
	exported   bool                    // 是否 exported
	signature  string                  // 函式簽名（不含 body）
	headline   string                  // doc 第一行非 @ai 的說明（可能為空）
	docAnns    []annotation.Annotation // doc 區塊的 @ai:* 標註（由 HypGo 解析）
	thinks     []string                // body 內的 @ai:think 原文（已去 // 前綴）
}

// extractFuncNodes 解析套件目錄內所有 .go 檔，回傳「帶 @ai 標註」的函式節點。
// 排除 @ai:generated by=hypgo 的框架生成碼；解析失敗的檔案略過不中斷。
func extractFuncNodes(p *pkgInfo, pkgNote string) []funcNode {
	//@ai:think intent=把套件內帶 @ai 標註的函式抽成行為節點，讓 HypGo 的意圖標註成為關係圖上的可導覽節點 model=claude-opus-4-8
	//@ai:think special=用 ParseComments 全解析以取得 doc 與 body 註解；單檔解析失敗則略過，與 scanPackages 的容錯一致 model=claude-opus-4-8
	var nodes []funcNode
	fset := token.NewFileSet()
	for _, base := range p.goFiles {
		full := filepath.Join(p.dir, base)
		f, err := parser.ParseFile(fset, full, nil, parser.ParseComments)
		if err != nil {
			continue
		}
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}

			docText := ""
			if fd.Doc != nil {
				docText = fd.Doc.Text()
			}
			docAnns := annotation.ParseAnnotations(docText) // 重用 HypGo 的 @ai 文法
			thinks := extractThink(f, fset, fd)

			if len(docAnns) == 0 && len(thinks) == 0 {
				continue // 無任何 @ai 標註 → 不建節點
			}
			if generatedByHypgo(docAnns) {
				continue // 非 HypGo：框架自產的膠水碼
			}

			display := fd.Name.Name
			if fd.Recv != nil && len(fd.Recv.List) > 0 {
				display = "(" + exprString(fset, fd.Recv.List[0].Type) + ")." + fd.Name.Name
			}

			nodes = append(nodes, funcNode{
				display:    display,
				noteName:   funcNoteName(pkgNote, display),
				pkgNote:    pkgNote,
				pkgName:    p.name,
				importPath: p.importPath,
				exported:   fd.Name.IsExported(),
				signature:  funcSignature(fset, fd),
				headline:   docHeadline(docText),
				docAnns:    docAnns,
				thinks:     thinks,
			})
		}
	}
	sort.Slice(nodes, func(i, j int) bool { return nodes[i].display < nodes[j].display })
	return nodes
}

// extractThink 擷取函式體範圍內的 //@ai:think 註解原文（沿用 HypGo bodyHasThink 的範圍判定）。
func extractThink(f *ast.File, fset *token.FileSet, fd *ast.FuncDecl) []string {
	//@ai:think intent=取出 body 內的 @ai:think 原文帶入筆記，補上 pkg/annotation 不輸出 think 內容的缺口 model=claude-opus-4-8
	if fd.Body == nil {
		return nil
	}
	start := fset.Position(fd.Body.Lbrace).Offset
	end := fset.Position(fd.Body.Rbrace).Offset
	var out []string
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			pos := fset.Position(c.Pos()).Offset
			if pos <= start || pos >= end {
				continue
			}
			text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if strings.HasPrefix(text, "@ai:think") {
				out = append(out, text)
			}
		}
	}
	return out
}

// generatedByHypgo 判斷 doc 標註中是否帶 @ai:generated by=hypgo（框架生成碼）。
func generatedByHypgo(anns []annotation.Annotation) bool {
	//@ai:think intent=以 @ai:generated by=hypgo 作為「框架自產膠水」的訊號，落實非 HypGo 的排除規則 model=claude-opus-4-8
	for _, a := range anns {
		if a.Type == annotation.Generated && strings.Contains(a.Value, "by=hypgo") {
			return true
		}
	}
	return false
}

// docHeadline 取 doc 文字中第一行非 @ai:、非空白的說明行（無則回空字串）。
func docHeadline(docText string) string {
	//@ai:think intent=取出人類可讀的首句說明作為節點摘要，跳過 @ai 標註行 model=claude-opus-4-8
	for _, line := range strings.Split(docText, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "@ai:") {
			continue
		}
		return line
	}
	return ""
}

// funcSignature 印出函式簽名（不含 body 與 doc），用 go/printer 確保格式與原始碼一致。
func funcSignature(fset *token.FileSet, fd *ast.FuncDecl) string {
	//@ai:think intent=以 go/printer 重建乾淨簽名（Body 設 nil），讓節點顯示與原始碼一致的型別資訊 model=claude-opus-4-8
	sig := &ast.FuncDecl{Recv: fd.Recv, Name: fd.Name, Type: fd.Type}
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, sig); err != nil {
		return "func " + fd.Name.Name + "(...)"
	}
	return buf.String()
}

// exprString 將 AST 運算式（如接收者型別）印成原始碼字串。
func exprString(fset *token.FileSet, e ast.Expr) string {
	//@ai:think intent=把接收者型別等運算式還原為字串，組出方法的顯示名 (*T).Method model=claude-opus-4-8
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, e); err != nil {
		return ""
	}
	return buf.String()
}

// funcNoteName 由套件筆記名與函式顯示名組出唯一且合法的節點檔名。
func funcNoteName(pkgNote, display string) string {
	//@ai:think intent=以「套件筆記名.函式名」組出唯一檔名，避免跨套件同名函式互相覆蓋 model=claude-opus-4-8
	return pkgNote + "." + stripFuncSym(display)
}

// stripFuncSym 去掉函式顯示名中的 ( ) * 與空白，產生可作為檔名片段或比對鍵的字串。
// 同時用於 funcNoteName 與 handler 比對，確保「(*T).M」「(T).M」「pkg.(*T).M」正規化後一致。
func stripFuncSym(s string) string {
	//@ai:think intent=統一去除接收者語法符號，讓檔名與 handler 比對鍵在指標/值接收者間一致 model=claude-opus-4-8
	return strings.NewReplacer("(", "", ")", "", "*", "", " ", "").Replace(s)
}

// renderFuncNote 產生單一函式行為節點的 Obsidian 筆記內容。
// usedByRoutes 為「被哪些路由使用」的反向連結清單（非 handler 則為空）。
func renderFuncNote(fn funcNode, usedByRoutes []string) string {
	//@ai:think intent=把函式的簽名、摘要與 @ai 標註渲染成筆記，並回連所屬套件讓 graph view 串起來 model=claude-opus-4-8
	//@ai:think special=若此函式是路由 handler，列出反向連結（被哪些路由使用）並回連 HypGo Context model=claude-opus-4-8
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("tags: [go-func]\n")
	b.WriteString("package: " + fn.pkgName + "\n")
	b.WriteString("import: \"" + fn.importPath + "\"\n")
	b.WriteString("func: \"" + fn.display + "\"\n")
	b.WriteString("exported: " + strconv.FormatBool(fn.exported) + "\n")
	if len(usedByRoutes) > 0 {
		b.WriteString("handler: true\n")
	}
	b.WriteString("---\n\n")

	b.WriteString("# " + fn.display + "\n\n")
	b.WriteString("```go\n" + fn.signature + "\n```\n\n")
	if fn.headline != "" {
		b.WriteString("> " + fn.headline + "\n\n")
	}
	b.WriteString("所屬套件：[[" + fn.pkgNote + "]]\n\n")

	if len(usedByRoutes) > 0 {
		b.WriteString("## 被路由使用 (Used by routes)\n\n")
		for _, r := range usedByRoutes {
			b.WriteString("- " + r + "\n")
		}
		b.WriteString("\n來源：[[HypGo Context]]\n\n")
	}

	if len(fn.docAnns) > 0 {
		b.WriteString("## @ai 標註 (doc)\n\n")
		for _, a := range fn.docAnns {
			if a.Value == "" {
				b.WriteString("- **" + string(a.Type) + "**\n")
			} else {
				b.WriteString("- **" + string(a.Type) + "** — " + a.Value + "\n")
			}
		}
		b.WriteString("\n")
	}

	if len(fn.thinks) > 0 {
		b.WriteString("## 意圖 (@ai:think)\n\n")
		for _, t := range fn.thinks {
			content := strings.TrimSpace(strings.TrimPrefix(t, "@ai:think"))
			b.WriteString("- " + content + "\n")
		}
		b.WriteString("\n")
	}
	return b.String()
}
