// Package services ...
//
// @ai:generated by=heuristic date=2026-06-18
// @ai:modified by=claude-opus-4-8 date=2026-06-19 reason=路由 handler 直接連到函式行為節點（buildNoteByHandler / handlerFuncNote），找不到才退回套件層級
// @ai:purpose TODO: 說明此套件的職責
// @ai:owner team=unknown
package services

// hyp_context.go 處理 HypGo 專案的 .hyp/context.yaml：
// 當被掃描的 Go 專案是 HypGo 專案（存在 .hyp/context.yaml）時，解析其內容
// （路由 schema、資料模型、伺服器設定），併入 Obsidian map，並把路由的 handler
// 優先連到對應的「函式行為節點」（帶 @ai 標註者），找不到才退回所屬套件筆記，
// 讓 API 結構與其 handler 的意圖直接出現在關係圖中。

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// hypContext 對應 .hyp/context.yaml 的子集（只取產 map 需要的欄位；
// yaml.v3 會忽略未列出的欄位，因此對 HypGo 版本差異具韌性）。
type hypContext struct {
	Version     string     `yaml:"version"`
	Framework   string     `yaml:"framework"`
	GeneratedAt string     `yaml:"generated_at"`
	Server      hypServer  `yaml:"server"`
	Routes      []hypRoute `yaml:"routes"`
	Models      []hypModel `yaml:"models"`
	Middleware  []string   `yaml:"middleware"`
	Lint        *hypLint   `yaml:"lint"`
}

type hypServer struct {
	Addr     string `yaml:"addr"`
	Protocol string `yaml:"protocol"`
	TLS      bool   `yaml:"tls"`
}

type hypRoute struct {
	Protocol     string         `yaml:"protocol"`
	Command      string         `yaml:"command"`
	Method       string         `yaml:"method"`
	Path         string         `yaml:"path"`
	Summary      string         `yaml:"summary"`
	Tags         []string       `yaml:"tags"`
	InputType    string         `yaml:"input_type"`
	OutputType   string         `yaml:"output_type"`
	HandlerNames []string       `yaml:"handler_names"`
	Responses    map[int]string `yaml:"responses"`
}

type hypModel struct {
	Name   string     `yaml:"name"`
	Table  string     `yaml:"table"`
	Fields []hypField `yaml:"fields"`
}

type hypField struct {
	Name   string `yaml:"name"`
	GoType string `yaml:"go_type"`
	PK     bool   `yaml:"pk"`
}

type hypLint struct {
	Coverage   string `yaml:"coverage"`
	Total      int    `yaml:"total"`
	WithSchema int    `yaml:"with_schema"`
}

// loadHypContext 於 module root（其次為 inputDir）尋找並解析 .hyp/context.yaml。
// 回傳解析結果、來源路徑，以及是否找到。解析失敗視同未找到。
// @ai:generated by=heuristic date=2026-06-18
// @ai:owner team=unknown
func loadHypContext(moduleRoot, inputDir string) (*hypContext, string, bool) {
	//@ai:think intent=偵測被掃描專案是否為 HypGo 專案，是則解析 .hyp/context.yaml 以併入 API 結構 model=claude-opus-4-8
	//@ai:think special=解析失敗視同未找到而非報錯，讓非 HypGo 專案也能正常產 map model=claude-opus-4-8
	candidates := []string{filepath.Join(moduleRoot, ".hyp", "context.yaml")}
	if inputDir != moduleRoot {
		candidates = append(candidates, filepath.Join(inputDir, ".hyp", "context.yaml"))
	}
	for _, p := range candidates {
		data, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		var hc hypContext
		if err := yaml.Unmarshal(data, &hc); err != nil {
			continue
		}
		return &hc, p, true
	}
	return nil, "", false
}

// buildNoteByPkgName 由套件名稱對應到其筆記名，供 handler 連結使用。
// 同名套件（罕見）視為歧義並排除，以免連到錯誤的筆記。
// @ai:generated by=heuristic date=2026-06-18
// @ai:owner team=unknown
func buildNoteByPkgName(pkgs []*pkgInfo, noteByImport map[string]string) map[string]string {
	//@ai:think intent=建立套件名→筆記名對照，供路由 handler 連回所屬套件 model=claude-opus-4-8
	//@ai:think special=同名套件視為歧義並排除，寧可不連也不連錯 model=claude-opus-4-8
	byName := make(map[string]string)
	dup := make(map[string]bool)
	for _, p := range pkgs {
		if _, ok := byName[p.name]; ok {
			dup[p.name] = true
			continue
		}
		byName[p.name] = noteByImport[p.importPath]
	}
	for n := range dup {
		delete(byName, n)
	}
	return byName
}

// buildNoteByHandler 建立「正規化 handler 名 → 函式節點筆記名」對照，供路由直接連到 handler 的行為節點。
//
// HypGo 的 handler 名形如 "controllers.(*UserController).Create"（見 hypgo router.nameOfFunction：
// 取 import path 末段 + 方法/函式名、去 -fm）。鍵以 path.Base(importPath) 當套件段、stripFuncSym
// 去掉 ( ) * 做正規化，使指標／值接收者與自由函式都能一致比對。
// 同鍵（同末段套件名 + 同函式）視為歧義並排除，寧可退回套件層級也不連錯。
// @ai:generated by=claude-opus-4-8 date=2026-06-19
func buildNoteByHandler(pkgs []*pkgInfo) map[string]string {
	//@ai:think intent=建立 handler→函式節點對照，讓 HypGo 路由直接連到 handler 的 @ai 行為節點 model=claude-opus-4-8
	//@ai:think special=以 path.Base(importPath) 對齊 runtime handler 的套件末段，並用 stripFuncSym 統一指標/值接收者；同鍵歧義則排除 model=claude-opus-4-8
	byHandler := make(map[string]string)
	dup := make(map[string]bool)
	for _, p := range pkgs {
		base := path.Base(p.importPath)
		for _, fn := range p.funcs {
			key := base + "." + stripFuncSym(fn.display)
			if _, ok := byHandler[key]; ok {
				dup[key] = true
				continue
			}
			byHandler[key] = fn.noteName
		}
	}
	for k := range dup {
		delete(byHandler, k)
	}
	return byHandler
}

// handlerFuncNote 由 handler 名（如 "controllers.(*UserController).Create"）對應到函式節點筆記名；
// 找不到則回傳空字串（由呼叫端退回套件層級連結）。
// @ai:generated by=claude-opus-4-8 date=2026-06-19
func handlerFuncNote(handler string, noteByHandler map[string]string) string {
	//@ai:think intent=把 handler 名正規化後查對照表，命中即連到該函式行為節點 model=claude-opus-4-8
	if handler == "" {
		return ""
	}
	return noteByHandler[stripFuncSym(handler)]
}

// buildRoutesByFuncNote 建立「函式節點筆記名 → 使用它的路由顯示字串清單」，
// 供函式節點頁面列出反向連結（被哪些路由使用）。比對邏輯與 markdown 一致：
// 逐一掃 HandlerNames，取第一個命中函式節點者。每個節點的清單已排序以求穩定輸出。
// @ai:generated by=claude-opus-4-8 date=2026-06-19
func buildRoutesByFuncNote(hc *hypContext, noteByHandler map[string]string) map[string][]string {
	//@ai:think intent=反轉 route→handler 關係，讓函式節點頁能列出「被哪些路由使用」 model=claude-opus-4-8
	//@ai:think special=比對邏輯與 markdown 對齊（取第一個命中函式節點的 handler），並排序輸出避免每次產圖差異 model=claude-opus-4-8
	out := make(map[string][]string)
	for _, rt := range hc.Routes {
		note := ""
		for _, h := range rt.HandlerNames {
			if n := handlerFuncNote(h, noteByHandler); n != "" {
				note = n
				break
			}
		}
		if note == "" {
			continue
		}
		ref := rt.shortRef()
		if rt.Summary != "" {
			ref += " — " + rt.Summary
		}
		out[note] = append(out[note], ref)
	}
	for k := range out {
		sort.Strings(out[k])
	}
	return out
}

// shortRef 回傳路由用於反向連結清單的簡短顯示（REST 用 method+path，其餘用 [proto] command）。
// @ai:generated by=claude-opus-4-8 date=2026-06-19
func (r hypRoute) shortRef() string {
	//@ai:think intent=產生路由的簡短可讀標示，供函式節點的「被路由使用」清單顯示 model=claude-opus-4-8
	if r.protoOrRest() == "rest" {
		return "**" + r.Method + "** `" + r.Path + "`"
	}
	return "[" + r.protoOrRest() + "] `" + r.Command + "`"
}

// renderHypContextNote 產生「HypGo Context」筆記，內含路由、模型與設定摘要。
// @ai:generated by=heuristic date=2026-06-18
// @ai:owner team=unknown
func renderHypContextNote(hc *hypContext, srcPath string, noteByPkgName, noteByHandler map[string]string) string {
	//@ai:think intent=把 manifest 的路由／模型／設定渲染成 HypGo Context 筆記，讓 API 結構出現在關係圖 model=claude-opus-4-8
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("tags: [hypgo, context]\n")
	if hc.Framework != "" {
		b.WriteString("framework: " + hc.Framework + "\n")
	}
	if hc.Version != "" {
		b.WriteString("version: \"" + hc.Version + "\"\n")
	}
	b.WriteString("---\n\n")

	b.WriteString("# HypGo Context\n\n")
	b.WriteString("來源：`" + filepath.ToSlash(srcPath) + "`\n\n")
	if hc.Framework != "" {
		line := "- 框架：" + hc.Framework
		if hc.Version != "" {
			line += " v" + hc.Version
		}
		b.WriteString(line + "\n")
	}
	if hc.GeneratedAt != "" {
		b.WriteString("- 產生時間：" + hc.GeneratedAt + "\n")
	}
	if hc.Server.Addr != "" || hc.Server.Protocol != "" {
		b.WriteString(fmt.Sprintf("- 伺服器：`%s`（協議 %s、TLS %v）\n", hc.Server.Addr, hc.Server.Protocol, hc.Server.TLS))
	}
	if hc.Lint != nil && hc.Lint.Coverage != "" {
		b.WriteString("- Schema 覆蓋率：" + hc.Lint.Coverage + "\n")
	}
	if len(hc.Middleware) > 0 {
		b.WriteString("- Middleware：" + strings.Join(hc.Middleware, "、") + "\n")
	}
	b.WriteString("\n")

	b.WriteString("## 路由 (Routes)\n\n")
	if len(hc.Routes) == 0 {
		b.WriteString("_（manifest 未含任何路由）_\n\n")
	} else {
		routes := append([]hypRoute(nil), hc.Routes...)
		sort.Slice(routes, func(i, j int) bool {
			if pi, pj := routes[i].protoOrRest(), routes[j].protoOrRest(); pi != pj {
				return pi < pj
			}
			return routes[i].label() < routes[j].label()
		})
		for _, rt := range routes {
			b.WriteString("- " + rt.markdown(noteByPkgName, noteByHandler) + "\n")
		}
		b.WriteString("\n")
	}

	if len(hc.Models) > 0 {
		b.WriteString("## 資料模型 (Models)\n\n")
		for _, m := range hc.Models {
			head := "- **" + m.Name + "**"
			if m.Table != "" {
				head += " — 資料表 `" + m.Table + "`"
			}
			b.WriteString(head + "\n")
			for _, f := range m.Fields {
				row := "    - " + f.Name + " `" + f.GoType + "`"
				if f.PK {
					row += "（PK）"
				}
				b.WriteString(row + "\n")
			}
		}
		b.WriteString("\n")
	}

	return b.String()
}

// protoOrRest 回傳協議，空字串視為 "rest"。
// @ai:generated by=heuristic date=2026-06-18
// @ai:owner team=unknown
func (r hypRoute) protoOrRest() string {
	//@ai:think intent=把空 Protocol 正規化為 rest，統一後續排序與顯示判斷 model=claude-opus-4-8
	if r.Protocol == "" {
		return "rest"
	}
	return r.Protocol
}

// label 回傳排序與顯示用的識別字串。
// @ai:generated by=heuristic date=2026-06-18
// @ai:owner team=unknown
func (r hypRoute) label() string {
	//@ai:think intent=產生路由的排序／顯示鍵（REST 用 method+path，其餘用 command） model=claude-opus-4-8
	if r.protoOrRest() == "rest" {
		return r.Method + " " + r.Path
	}
	return r.Command
}

// markdown 產生單一路由的條目，並把 handler 優先連到函式行為節點、否則退回套件筆記。
// @ai:generated by=heuristic date=2026-06-18
// @ai:modified by=claude-opus-4-8 date=2026-06-19 reason=handler 優先連函式節點，找不到才退回套件
// @ai:owner team=unknown
func (r hypRoute) markdown(noteByPkgName, noteByHandler map[string]string) string {
	//@ai:think intent=渲染單一路由條目，handler 優先連到其函式行為節點以呈現意圖，找不到才退回所屬套件 model=claude-opus-4-8
	//@ai:think special=逐一掃 HandlerNames 取第一個命中函式節點者（相容 handler 名在 [0] 或最後一個的情況），皆未命中再用 [0] 退回套件 model=claude-opus-4-8
	var sb strings.Builder
	if r.protoOrRest() == "rest" {
		sb.WriteString("**" + r.Method + "** `" + r.Path + "`")
	} else {
		sb.WriteString("[" + r.protoOrRest() + "] `" + r.Command + "`")
	}
	if r.Summary != "" {
		sb.WriteString(" — " + r.Summary)
	}
	if r.InputType != "" || r.OutputType != "" {
		in, out := r.InputType, r.OutputType
		if in == "" {
			in = "—"
		}
		if out == "" {
			out = "—"
		}
		sb.WriteString(fmt.Sprintf("（%s → %s）", in, out))
	}
	if len(r.HandlerNames) > 0 {
		linked := ""
		for _, h := range r.HandlerNames {
			if note := handlerFuncNote(h, noteByHandler); note != "" {
				linked = note
				break
			}
		}
		if linked != "" {
			sb.WriteString(" → [[" + linked + "]]")
		} else if note := handlerNote(r.HandlerNames[0], noteByPkgName); note != "" {
			sb.WriteString(" → [[" + note + "]]")
		}
	}
	return sb.String()
}

// handlerNote 由 handler 名稱（如 "controllers.(*UserController).Create"）取其
// 套件名，對應到該套件的筆記名；找不到則回傳空字串。
// @ai:generated by=heuristic date=2026-06-18
// @ai:owner team=unknown
func handlerNote(handler string, noteByPkgName map[string]string) string {
	//@ai:think intent=從 handler 全名取套件段對應到筆記名，建立路由與套件的關聯 model=claude-opus-4-8
	//@ai:think special=取第一個 . 前的套件名，找不到對照則回空字串避免死連結 model=claude-opus-4-8
	if handler == "" {
		return ""
	}
	pkg := handler
	if i := strings.IndexByte(pkg, '.'); i >= 0 {
		pkg = pkg[:i]
	}
	return noteByPkgName[pkg]
}
