// @ai:generated by=claude-opus-4-8 date=2026-06-18
// @ai:modified by=claude-opus-4-7 date=2026-06-19 reason=接上 stderr logger，讓 AutoSync 把 LLM 啟用訊息與失敗原因印出來
package main

// tools/genctx 按需產生 .hyp/context.yaml（依 HypGo CLI / 桌面 init 樣板）。
//
// 桌面 / CLI 專案的 schema 在 main.go 啟動時登錄到 schema.Global()，但「不在 runtime
// 寫檔」——避免終端使用者每次執行程式都動到 .hyp/context.yaml。因此 manifest 改由本
// 工具獨立、按需產生：
//
//	go run ./tools/genctx
//
// 流程：呼叫各層的 RegisterSchemas() 填滿 Schema Registry，再用 manifest.AutoSync
// （router 傳 nil，路由全部來自 schema.Global() 的非 REST 協議）原子寫入
// .hyp/context.yaml。等同 Web/API 由 server.Start() AutoSync 所做的事，只是手動觸發。

import (
	"fmt"
	"os"

	"github.com/maoxiaoyue/hypgo/pkg/logger"
	"github.com/maoxiaoyue/hypgo/pkg/manifest"

	"map/app/commands"
	"map/app/views"
)

// main 填滿 Schema Registry 後把 manifest 寫到 .hyp/context.yaml。
func main() {
	//@ai:think intent=按需重建 .hyp/context.yaml：先登錄 schema 再由 AutoSync 收集寫檔，取代桌面/CLI 缺少的 runtime AutoSync model=claude-opus-4-8
	//@ai:think special=router 與 config 皆傳 nil——本專案無 HTTP router，路由全部來自 schema.Global()，且桌面/CLI 無伺服器設定 model=claude-opus-4-8

	// 1. 填滿 Schema Registry（與 main.go 啟動時呼叫的相同函式）
	commands.RegisterSchemas() // Protocol "cli"（map 命令、-i / -o）
	views.RegisterSchemas()    // Protocol "desktop"（view/main）

	// stderr logger：AutoSync 會把「LLM enrichment enabled」與每條 enricher 錯誤
	// 印到 stderr，避免「.hyp/llm.yaml 設定錯誤但 LLM 靜默退回純推斷」的盲區
	log, _ := logger.New("info", "stderr", os.Stderr, false)

	// 2. 收集並原子寫入 .hyp/context.yaml（temp file + rename）
	//    AutoSync 會自動探測同目錄的 .hyp/llm.yaml；若 mode!=none 套用 LLM 增強
	sync := manifest.NewAutoSync(
		manifest.AutoSyncConfig{Enabled: true},
		nil, // *router.Router：無 HTTP router
		nil, // *config.Config：桌面/CLI 無 server 區段
		log, // *logger.Logger：stderr，露出 LLM 訊息
	)
	if err := sync.Sync(); err != nil {
		fmt.Fprintf(os.Stderr, "genctx: 寫入 %s 失敗：%v\n", manifest.DefaultContextPath, err)
		os.Exit(1)
	}
	fmt.Printf("genctx: 已產生 %s\n", manifest.DefaultContextPath)
}
