// @ai:generated by=claude-opus-4-8 date=2026-06-17
// @ai:modified by=claude-opus-4-8 date=2026-06-19 reason=把 --windows 納入 schema，讓所有 CLI 參數描述集中於 MapCommand.Params；BindFlags/MissingRequired 改為型別感知
package commands

// schema.go 是 GoMap 命令列模式的進入點（依 HypGo CLI init 樣板）。
// RegisterSchemas() 由 main 啟動時呼叫一次，把命令以 Protocol "cli" 登錄到
// schema.Global()，讓 hyp context / lint / contract 無需讀實作即可理解介面。
// 所有 CLI 參數 (--windows / -i / -o) 都由 MapCommand.Params 這份 schema 描述
// （單一事實來源）：BindFlags 依各 Param 的 Type 註冊對應型別的旗標，main 直接消費。

import (
	"flag"
	"map/app/models"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/schema"
)

// MapCommand 是 GoMap 命令列命令的 schema 定義（Protocol "cli"）。
// Params 描述全部 CLI 參數：--windows 切換 GUI、-i 輸入、-o 輸出。
var MapCommand = schema.Route{
	Protocol:   "cli",
	Command:    "map",
	Summary:    "將指定的 Go 專案目錄轉成 Obsidian map",
	Tags:       []string{"gomap"},
	Input:      models.CLIInput{},
	Output:     models.MapResult{},
	InputName:  schema.TypeName(models.CLIInput{}),
	OutputName: schema.TypeName(models.MapResult{}),
	Params: []schema.ParamSchema{
		{Name: "windows", In: "flag", Required: false, Type: "bool", Desc: "開啟圖形視窗 (GUI) 模式；不指定則為命令列模式"},
		{Name: "i", In: "flag", Required: true, Type: "string", Desc: "輸入：要掃描的 Go 專案目錄"},
		{Name: "o", In: "flag", Required: true, Type: "string", Desc: "輸出：產生 Obsidian map 的目錄 (vault)"},
	},
}

// RegisterSchemas 向 Schema Registry 註冊所有 CLI 命令（Protocol "cli"）。
func RegisterSchemas() {
	//@ai:think intent=啟動時把 CLI 命令登錄到 schema.Global()，讓 hyp lint / context 不必讀實作即可理解介面 model=claude-opus-4-8
	schema.Global().Register(MapCommand)
}

// FlagToken 將旗標名加上前綴：單字元用 "-x"、多字元用 "--xx"。
func FlagToken(name string) string {
	//@ai:think intent=依旗標名長度補上 - 或 -- 前綴，讓 usage 與缺漏訊息顯示一致 model=claude-opus-4-8
	if len(name) == 1 {
		return "-" + name
	}
	return "--" + name
}

// BoundFlags 持有依 MapCommand.Params 註冊後的旗標值指標，依型別分流（string / bool 各一張表），
// 讓呼叫端以 String / Bool 取值而不必關心底層型別。
type BoundFlags struct {
	strs  map[string]*string
	bools map[string]*bool
}

// String 回傳字串旗標的值；未註冊或非字串型別則回空字串。
func (b BoundFlags) String(name string) string {
	//@ai:think intent=安全取字串旗標值，未註冊回空字串避免 nil 解參考 model=claude-opus-4-8
	if p, ok := b.strs[name]; ok && p != nil {
		return *p
	}
	return ""
}

// Bool 回傳布林旗標的值；未註冊或非布林型別則回 false。
func (b BoundFlags) Bool(name string) bool {
	//@ai:think intent=安全取布林旗標值，未註冊回 false 作為合理預設 model=claude-opus-4-8
	if p, ok := b.bools[name]; ok && p != nil {
		return *p
	}
	return false
}

// BindFlags 依 MapCommand 的 Params 在 fs 上註冊旗標（schema 為單一事實來源），
// 依每個 Param 的 Type 分流（"bool" → fs.Bool，其餘 → fs.String），
// 回傳 BoundFlags 供解析後以 String / Bool 取值。
func BindFlags(fs *flag.FlagSet) BoundFlags {
	//@ai:think intent=由 schema 的 Params 動態註冊旗標，並依 Param.Type 分流 bool/string，使 schema 成為所有 CLI 參數的單一事實來源 model=claude-opus-4-8
	b := BoundFlags{
		strs:  make(map[string]*string, len(MapCommand.Params)),
		bools: make(map[string]*bool, len(MapCommand.Params)),
	}
	for _, p := range MapCommand.Params {
		switch p.Type {
		case "bool":
			b.bools[p.Name] = fs.Bool(p.Name, false, p.Desc)
		default:
			b.strs[p.Name] = fs.String(p.Name, "", p.Desc)
		}
	}
	return b
}

// MissingRequired 依 schema 檢查必填旗標，回傳尚未提供值者（含前綴），皆備齊則為空。
func MissingRequired(b BoundFlags) []string {
	//@ai:think intent=依 schema 檢查必填字串旗標是否齊備，回傳缺漏清單供 CLI 報錯 model=claude-opus-4-8
	//@ai:think special=布林旗標預設 false 恆有值，跳過以免把 mode 開關誤判為缺漏 model=claude-opus-4-8
	var missing []string
	for _, p := range MapCommand.Params {
		if !p.Required || p.Type == "bool" {
			continue
		}
		if strings.TrimSpace(b.String(p.Name)) == "" {
			missing = append(missing, FlagToken(p.Name))
		}
	}
	return missing
}
