// @ai:generated by=claude-opus-4-8 date=2026-06-17
package commands

// schema.go 是 GoMap 命令列模式的進入點（依 HypGo CLI init 樣板）。
// RegisterSchemas() 由 main 啟動時呼叫一次，把命令以 Protocol "cli" 登錄到
// schema.Global()，讓 hyp context / lint / contract 無需讀實作即可理解介面。
// 旗標 (-i / -o) 由 MapCommand.Params 這份 schema 驅動（單一事實來源）。

import (
	"flag"
	"strings"

	"map/app/models"

	"github.com/maoxiaoyue/hypgo/pkg/schema"
)

// MapCommand 是 GoMap 命令列命令 (-i / -o) 的 schema 定義（Protocol "cli"）。
var MapCommand = schema.Route{
	Protocol:   "cli",
	Command:    "map",
	Summary:    "將指定的 Go 專案目錄轉成 Obsidian map",
	Tags:       []string{"gomap"},
	Input:      models.CLIInput{},
	Output:     models.MapResult{},
	InputName:  schema.TypeName(models.CLIInput{}),
	OutputName: schema.TypeName(models.MapResult{}),
	Params: []schema.ParamSchema{
		{Name: "i", In: "flag", Required: true, Type: "string", Desc: "輸入：要掃描的 Go 專案目錄"},
		{Name: "o", In: "flag", Required: true, Type: "string", Desc: "輸出：產生 Obsidian map 的目錄 (vault)"},
	},
}

// RegisterSchemas 向 Schema Registry 註冊所有 CLI 命令（Protocol "cli"）。
func RegisterSchemas() {
	schema.Global().Register(MapCommand)
}

// FlagToken 將旗標名加上前綴：單字元用 "-x"、多字元用 "--xx"。
func FlagToken(name string) string {
	if len(name) == 1 {
		return "-" + name
	}
	return "--" + name
}

// BindFlags 依 MapCommand 的 Params 在 fs 上註冊旗標（schema 為單一事實來源），
// 回傳「旗標名 → 值指標」對照表，供解析後取值。
func BindFlags(fs *flag.FlagSet) map[string]*string {
	vals := make(map[string]*string, len(MapCommand.Params))
	for _, p := range MapCommand.Params {
		vals[p.Name] = fs.String(p.Name, "", p.Desc)
	}
	return vals
}

// MissingRequired 依 schema 檢查必填旗標，回傳尚未提供值者（含前綴），皆備齊則為空。
func MissingRequired(vals map[string]*string) []string {
	var missing []string
	for _, p := range MapCommand.Params {
		if !p.Required {
			continue
		}
		if v, ok := vals[p.Name]; !ok || strings.TrimSpace(*v) == "" {
			missing = append(missing, FlagToken(p.Name))
		}
	}
	return missing
}
