// @ai:generated by=claude-opus-4-8 date=2026-06-17
package views

// schema.go 是 GoMap 桌面視圖的進入點（依 HypGo 桌面 init 樣板）。
// RegisterSchemas() 由 main 啟動時呼叫一次，把視圖以 Protocol "desktop" 登錄到
// schema.Global()，讓 hyp context / lint / contract 無需讀實作即可理解介面。

import "github.com/maoxiaoyue/hypgo/pkg/schema"

// RegisterSchemas 向 Schema Registry 註冊所有桌面視圖（Protocol "desktop"）。
func RegisterSchemas() {
	registerDesktop("view/main", "GoMap 主畫面：選擇 Go 專案目錄並建立 Obsidian map", nil, nil)
	// 由 hyp generate view <name> 新增後補登：
	// registerDesktop("view/settings", "設定視圖", nil, nil)
}

// registerDesktop 等同 schema.RegisterDesktop（此 hypgo 版本未提供該便捷函式），
// 以 Protocol "desktop" 將視圖登錄到 schema.Global()，並自動補齊 Input/Output 型別名稱。
func registerDesktop(command, summary string, input, output any) {
	route := schema.Route{Protocol: "desktop", Command: command, Summary: summary, Input: input, Output: output}
	if input != nil {
		route.InputName = schema.TypeName(input)
	}
	if output != nil {
		route.OutputName = schema.TypeName(output)
	}
	schema.Global().Register(route)
}
